# Generated by Django 3.2.9 on 2022-04-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAddress',
        ),
    ]
