# Generated by Django 3.2.9 on 2022-04-26 21:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0004_auto_20220425_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='header_text',
            field=models.CharField(max_length=60, null=True, verbose_name='Header Text'),
        ),
    ]
