# Generated by Django 3.2.9 on 2022-04-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(verbose_name='Street')),
                ('ext_number', models.CharField(max_length=10, verbose_name='External Number')),
                ('int_number', models.CharField(max_length=10, verbose_name='Internal Number')),
                ('colony', models.CharField(max_length=100, verbose_name='Colony')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('additional_notes', models.CharField(max_length=255, verbose_name='Additional Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
