# Generated by Django 3.2.9 on 2022-04-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220426_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='municipality',
            field=models.CharField(max_length=100, null=True, verbose_name='Municipality'),
        ),
    ]
