# Generated by Django 3.2.9 on 2022-04-26 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_clientaddress_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_phone_number', message='The number must be of 10 digits', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
