# Generated by Django 3.2.9 on 2022-04-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('sub_total', models.FloatField(verbose_name='Sub Total')),
                ('discount', models.FloatField(blank=True, default=0.0, verbose_name='Discount')),
                ('pay_method', models.CharField(choices=[('STORE', 'Deliver on Store'), ('ML', 'MERCADOLIBRE')], default='STORE', max_length=20, verbose_name='Payment Method')),
                ('pay_track', models.TextField(blank=True, null=True, verbose_name='Pay Tracking')),
                ('pay_status', models.CharField(choices=[('STORE', 'Pay on Store'), ('SUCCESS', 'Payed'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], default='STORE', max_length=20, verbose_name='Pay Status')),
                ('order_status', models.CharField(choices=[('STORE', 'Pay on Store'), ('PLEASE_CONTACT', 'Please call, we need more information'), ('FULLFILLED', 'Shipped'), ('DELIVER', 'Deliver')], default='STORE', max_length=20, verbose_name='Order Status')),
                ('ship_method', models.CharField(choices=[('STORE', 'Deliver on Store'), ('DHL', 'Deliver on DHL')], default='STORE', max_length=20, verbose_name='Shipping Method')),
                ('track_number', models.TextField(blank=True, null=True, verbose_name='Track Number')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('days', models.IntegerField(verbose_name='Day to deliver')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
